#pragma once
#define MODULE_LIBS "system/ulib/c_system/ulib/crypto_system/ulib/driver_system/ulib/fdio_system/ulib/zircon_"
#define MODULE_STATIC_LIBS "third_party/ulib/uboringssl_system/ulib/ddk_system/ulib/fbl_system/ulib/pretty_system/ulib/sync_system/ulib/zx_system/ulib/zxcpp"
#define MODULE_COMPILEFLAGS "-I./build-arm64-release/system/ulib/c/gen/include_-I./build-arm64-release/system/ulib/crypto/gen/include_-I./build-arm64-release/system/ulib/ddk/gen/include_-I./build-arm64-release/system/ulib/driver/gen/include_-I./build-arm64-release/system/ulib/fbl/gen/include_-I./build-arm64-release/system/ulib/fdio/gen/include_-I./build-arm64-release/system/ulib/pretty/gen/include_-I./build-arm64-release/system/ulib/sync/gen/include_-I./build-arm64-release/system/ulib/zircon/gen/include_-I./build-arm64-release/system/ulib/zx/gen/include_-I./build-arm64-release/system/ulib/zxcpp/gen/include_-I./build-arm64-release/third_party/ulib/uboringssl/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/crypto/include_-Isystem/ulib/ddk/include_-Isystem/ulib/driver/include_-Isystem/ulib/fbl/include_-Isystem/ulib/fdio/include_-Isystem/ulib/pretty/include_-Isystem/ulib/sync/include_-Isystem/ulib/zircon/include_-Isystem/ulib/zx/include_-Isystem/ulib/zxcpp/include_-Isystem/ulib/zxcrypt/include_-Ithird_party/ulib/musl/include_-Ithird_party/ulib/uboringssl/include_-fsanitize-undefined-trap-on-error_-fsanitize=integer-divide-by-zero,signed-integer-overflow"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64-release/config-user.h_./build-arm64-release/system/ulib/c/gen-hdr.stamp_./build-arm64-release/system/ulib/crypto/gen-hdr.stamp_./build-arm64-release/system/ulib/ddk/gen-hdr.stamp_./build-arm64-release/system/ulib/driver/gen-hdr.stamp_./build-arm64-release/system/ulib/fbl/gen-hdr.stamp_./build-arm64-release/system/ulib/fdio/gen-hdr.stamp_./build-arm64-release/system/ulib/pretty/gen-hdr.stamp_./build-arm64-release/system/ulib/sync/gen-hdr.stamp_./build-arm64-release/system/ulib/zircon/gen-hdr.stamp_./build-arm64-release/system/ulib/zx/gen-hdr.stamp_./build-arm64-release/system/ulib/zxcpp/gen-hdr.stamp_./build-arm64-release/third_party/ulib/uboringssl/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/zxcrypt/volume.cpp"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/crypto_system/ulib/ddk_system/ulib/driver_system/ulib/fbl_system/ulib/fdio_system/ulib/pretty_system/ulib/sync_system/ulib/zircon_system/ulib/zx_system/ulib/zxcpp_third_party/ulib/uboringssl"
#define MODULE_TYPE "userlib"

