#pragma once
#define MODULE_LIBS "system/ulib/fbl"
#define MODULE_STATIC_LIBS "system/ulib/hwreg"
#define MODULE_COMPILEFLAGS "-I./build-x64-release/system/ulib/fbl/gen/include_-I./build-x64-release/system/ulib/hwreg/gen/include_-Iglobal/include_-Isystem/ulib/edid/include_-Isystem/ulib/fbl/include_-Isystem/ulib/hwreg/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64-release/config-user.h_./build-x64-release/system/ulib/fbl/gen-hdr.stamp_./build-x64-release/system/ulib/hwreg/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/edid/edid.cpp"
#define MODULE_HEADER_DEPS "system/ulib/fbl_system/ulib/hwreg"
#define MODULE_TYPE "userlib"

