#pragma once
#define MODULE_LIBS "system/ulib/c"
#define MODULE_STATIC_LIBS "third_party/ulib/cksum"
#define MODULE_COMPILEFLAGS "-I./build-x64-release/system/ulib/c/gen/include_-I./build-x64-release/third_party/ulib/cksum/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/gpt/include_-Ithird_party/ulib/cksum/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64-release/config-user.h_./build-x64-release/system/ulib/c/gen-hdr.stamp_./build-x64-release/third_party/ulib/cksum/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/gpt/cros.c_system/ulib/gpt/gpt.c"
#define MODULE_HEADER_DEPS "system/ulib/c_third_party/ulib/cksum"
#define MODULE_TYPE "userlib"

