#pragma once
#define MODULE_LIBS ""
#define MODULE_STATIC_LIBS ""
#define MODULE_COMPILEFLAGS "-DTFTP_EFILIB_-Iglobal/include_-Isystem/ulib/tftp/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64/config-user.h"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/tftp/tftp.c"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "efilib"

