#pragma once
#define MODULE_LIBS "system/ulib/async.default_system/ulib/c_system/ulib/zircon"
#define MODULE_STATIC_LIBS "system/ulib/async"
#define MODULE_COMPILEFLAGS "-I./build-arm64-release/system/ulib/async.default/gen/include_-I./build-arm64-release/system/ulib/async/gen/include_-I./build-arm64-release/system/ulib/c/gen/include_-I./build-arm64-release/system/ulib/zircon/gen/include_-Iglobal/include_-Isystem/ulib/async-loop/include_-Isystem/ulib/async.default/include_-Isystem/ulib/async/include_-Isystem/ulib/c/include_-Isystem/ulib/zircon/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64-release/config-user.h_./build-arm64-release/system/ulib/async.default/gen-hdr.stamp_./build-arm64-release/system/ulib/async/gen-hdr.stamp_./build-arm64-release/system/ulib/c/gen-hdr.stamp_./build-arm64-release/system/ulib/zircon/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/async-loop/loop.c"
#define MODULE_HEADER_DEPS "system/ulib/async_system/ulib/async.default_system/ulib/c_system/ulib/zircon"
#define MODULE_TYPE "userlib"

