#pragma once
#define MODULE_LIBS ""
#define MODULE_STATIC_LIBS ""
#define MODULE_COMPILEFLAGS "-I./build-arm64-release/system/ulib/c/gen/include_-I./build-arm64-release/system/ulib/fbl/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/explicit-memory/include_-Isystem/ulib/fbl/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64-release/config-user.h"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/explicit-memory/bytes.c"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/fbl"
#define MODULE_TYPE "userlib"

