#pragma once
#define MODULE_LIBS ""
#define MODULE_STATIC_LIBS "_system/ulib/c"
#define MODULE_COMPILEFLAGS "-I./build-arm64-release/system/ulib/c/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/zxcpp/include_-Ithird_party/ulib/musl/include_-fvisibility=hidden"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64-release/config-user.h_./build-arm64-release/system/ulib/c/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/zxcpp/new.cpp_system/ulib/zxcpp/pure_virtual.cpp_system/ulib/zxcpp/thread_atexit.cpp"
#define MODULE_HEADER_DEPS "system/ulib/c"
#define MODULE_TYPE "userlib"

