#pragma once
#define MODULE_LIBS "system/ulib/c_system/ulib/zircon"
#define MODULE_STATIC_LIBS "system/ulib/pretty_system/ulib/zx_"
#define MODULE_COMPILEFLAGS "-I./build-x64-release/system/ulib/c/gen/include_-I./build-x64-release/system/ulib/pretty/gen/include_-I./build-x64-release/system/ulib/zircon/gen/include_-I./build-x64-release/system/ulib/zx/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/pretty/include_-Isystem/ulib/unittest/include_-Isystem/ulib/zircon/include_-Isystem/ulib/zx/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64-release/config-user.h_./build-x64-release/system/ulib/c/gen-hdr.stamp_./build-x64-release/system/ulib/pretty/gen-hdr.stamp_./build-x64-release/system/ulib/zircon/gen-hdr.stamp_./build-x64-release/system/ulib/zx/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/unittest/all-tests.cpp_system/ulib/unittest/crash-handler.cpp_system/ulib/unittest/crash-list.cpp_system/ulib/unittest/unittest.cpp_system/ulib/unittest/watchdog.cpp"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/pretty_system/ulib/zircon_system/ulib/zx"
#define MODULE_TYPE "userlib"

