#pragma once
#define MODULE_LIBS "system/ulib/zircon_system/ulib/c"
#define MODULE_STATIC_LIBS "system/ulib/elfload"
#define MODULE_COMPILEFLAGS "-I./build-arm64/system/ulib/c/gen/include_-I./build-arm64/system/ulib/elfload/gen/include_-I./build-arm64/system/ulib/zircon/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/elfload/include_-Isystem/ulib/mini-process/include_-Isystem/ulib/zircon/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64/config-user.h_./build-arm64/system/ulib/c/gen-hdr.stamp_./build-arm64/system/ulib/elfload/gen-hdr.stamp_./build-arm64/system/ulib/zircon/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/ulib/mini-process/mini-process.c_system/ulib/mini-process/subprocess.c"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/elfload_system/ulib/zircon"
#define MODULE_TYPE "userlib"

