#pragma once
#define LK 1
#define _KERNEL 1
#define ZIRCON_TOOLCHAIN 1
#define WITH_PANIC_BACKTRACE 1
#define WITH_FRAME_POINTERS 1
#define WITH_DEBUG_LINEBUFFER 1
#define PLATFORM_SUPPORTS_PANIC_SHELL 1
#define WITH_PLATFORM_GENERIC_ARM 1
#define ARM_ISA_ARMV8 1
#define ARM_ISA_ARMV8A 1
#define SMP_MAX_CPUS 16
#define SMP_CPU_MAX_CLUSTERS 2
#define SMP_CPU_MAX_CLUSTER_CPUS 16
#define KERNEL_BASE 0xffffffff00000000
#define WITH_ARCH_ARM64 1
#define WITH_TOP 1
#define WITH_DEV_HDCP_AMLOGIC_S912 1
#define WITH_DEV_INTERRUPT_ARM_GIC_COMMON 1
#define WITH_DEV_INTERRUPT_ARM_GIC_V2 1
#define WITH_DEV_INTERRUPT_ARM_GIC_V3 1
#define WITH_DEV_IOMMU_DUMMY 1
#define WITH_DEV_PCIE 1
#define WITH_DEV_PDEV 1
#define WITH_DEV_PDEV_POWER 1
#define WITH_DEV_POWER_HISI 1
#define WITH_DEV_PSCI 1
#define WITH_DEV_TIMER_ARM_GENERIC 1
#define WITH_DEV_UART_AMLOGIC_S905 1
#define WITH_DEV_UART_NXP_IMX 1
#define WITH_DEV_UART_PL011 1
#define WITH_KERNEL 1
#define WITH_LIB_BITMAP 1
#define WITH_LIB_CBUF 1
#define WITH_LIB_DEBUGCOMMANDS 1
#define WITH_LIB_DEBUGLOG 1
#define WITH_LIB_KTRACE 1
#define WITH_LIB_MEMORY_LIMIT 1
#define WITH_LIB_MTRACE 1
#define WITH_LIB_USERBOOT 1
#define WITH_LIB_VERSION 1
#define WITH_OBJECT 1
#define WITH_PLATFORM 1
#define WITH_SYSCALLS 1
#define WITH_TARGET 1
#define WITH_TESTS 1
#define WITH_DEV_INTERRUPT 1
#define WITH_DEV_PDEV_INTERRUPT 1
#define WITH_DEV_PDEV_UART 1
#define WITH_DEV_UDISPLAY 1
#define WITH_LIB_CONSOLE 1
#define WITH_LIB_COUNTERS 1
#define WITH_LIB_CRYPTO 1
#define WITH_LIB_DEBUG 1
#define WITH_LIB_EXPLICIT_MEMORY 1
#define WITH_LIB_FBL 1
#define WITH_LIB_FIXED_POINT 1
#define WITH_LIB_HEADER_TESTS 1
#define WITH_LIB_HEAP 1
#define WITH_LIB_HYPERVISOR 1
#define WITH_LIB_LIBC 1
#define WITH_LIB_OOM 1
#define WITH_LIB_PCI 1
#define WITH_LIB_POW2_RANGE_ALLOCATOR 1
#define WITH_LIB_REGION_ALLOC 1
#define WITH_LIB_UNITTEST 1
#define WITH_LIB_USER_COPY 1
#define WITH_LIB_VDSO 1
#define WITH_LIB_ZXCPP 1
#define WITH_VM 1
#define WITH_ARCH_ARM64_HYPERVISOR 1
#define WITH_DEV_HW_RNG 1
#define WITH_LIB_GFX 1
#define WITH_LIB_GFXCONSOLE 1
#define WITH_LIB_HEAP_CMPCTMALLOC 1
#define WITH_LIB_IO 1
#define WITH_LIB_PRETTY 1
#define WITH_LIB_CRYPTOLIB 1
#define WITH_LIB_JITTERENTROPY 1
#define WITH_LIB_QRCODEGEN 1
#define WITH_LIB_UBORINGSSL 1
#define PROJECT_ARM64 1
#define PROJECT "arm64"
#define TARGET_ARM64 1
#define TARGET "arm64"
#define PLATFORM_GENERIC_ARM 1
#define PLATFORM "generic-arm"
#define ARCH_ARM64 1
#define ARCH "arm64"
#define BOOT_HEADER_SIZE 0x50
#define KERNEL_IMAGE "./build-arm64/zircon.elf.bin"
#define KERNEL_INCLUDES "-I./build-arm64_-Ikernel/include_-Ikernel/platform/generic-arm/include_-Ikernel/arch/arm64/include_-Ikernel/top/include_-Ikernel/dev/hdcp/amlogic_s912/include_-Ikernel/dev/interrupt/arm_gic/common/include_-Ikernel/dev/interrupt/arm_gic/v2/include_-Ikernel/dev/interrupt/arm_gic/v2/include_-Ikernel/dev/interrupt/arm_gic/v3/include_-Ikernel/dev/iommu/dummy/include_-Ikernel/dev/pcie/include_-Ikernel/dev/pdev/include_-Ikernel/dev/pdev/power/include_-Ikernel/dev/power/hisi/include_-Ikernel/dev/psci/include_-Ikernel/dev/timer/arm_generic/include_-Ikernel/dev/uart/amlogic_s905/include_-Ikernel/dev/uart/nxp-imx/include_-Ikernel/dev/uart/pl011/include_-Ikernel/kernel/include_-Isystem/ulib/bitmap/include_-Ikernel/lib/bitmap/include_-Ikernel/lib/cbuf/include_-Ikernel/lib/debugcommands/include_-Ikernel/lib/debuglog/include_-Ikernel/lib/ktrace/include_-Ikernel/lib/memory_limit/include_-Ikernel/lib/mtrace/include_-Ikernel/lib/userboot/include_-Ikernel/lib/version/include_-Ikernel/object/include_-Ikernel/platform/include_-Ikernel/syscalls/include_-Ikernel/target/include_-Ikernel/tests/include_-Ikernel/dev/interrupt/include_-Ikernel/dev/pdev/interrupt/include_-Ikernel/dev/pdev/uart/include_-Ikernel/dev/udisplay/include_-Ikernel/lib/console/include_-Ikernel/lib/counters/include_-Ikernel/lib/crypto/include_-Ikernel/lib/debug/include_-Isystem/ulib/explicit-memory/include_-Ikernel/lib/explicit-memory/include_-Ikernel/lib/fbl/include_-Isystem/ulib/fbl/include_-Ikernel/lib/fbl/include_-Ikernel/lib/fixed_point/include_-Ikernel/lib/header_tests/include_-Ikernel/lib/heap/include_-Ikernel/lib/heap/include_-Ikernel/lib/hypervisor/include_-Ikernel/lib/libc/include_-Ikernel/lib/oom/include_-Ikernel/lib/pci/include_-Ikernel/lib/pci/include_-Ikernel/lib/pow2_range_allocator/include_-Isystem/ulib/region-alloc/include_-Ikernel/lib/region-alloc/include_-Ikernel/lib/unittest/include_-Ikernel/lib/user_copy/include_-Ikernel/lib/vdso/include_-Isystem/ulib/zxcpp/include_-Ikernel/lib/zxcpp/include_-Ikernel/vm/include_-Ikernel/arch/arm64/hypervisor/include_-Ikernel/dev/hw_rng/include_-Ikernel/lib/gfx/include_-Ikernel/lib/gfxconsole/include_-Ikernel/lib/heap/cmpctmalloc/include_-Ikernel/lib/io/include_-Isystem/ulib/pretty/include_-Ikernel/lib/pretty/include_-Ithird_party/ulib/cryptolib/include_-Ithird_party/lib/cryptolib/include_-Ithird_party/lib/jitterentropy/include_-Ithird_party/lib/jitterentropy/include_-Ithird_party/ulib/qrcodegen/include_-Ithird_party/lib/qrcodegen/include_-Ithird_party/ulib/uboringssl/include_-Ithird_party/lib/uboringssl/include"
#define KERNEL_COMPILEFLAGS "-ffreestanding_-include_./build-arm64/config-kernel.h_-Wformat=2_-Wvla_-Wformat-signedness_-fno-exceptions_-fno-unwind-tables_-fno-omit-frame-pointer_-mgeneral-regs-only_-fPIE_-include_kernel/include/hidden.h"
#define KERNEL_CFLAGS "-Wmissing-prototypes"
#define KERNEL_CPPFLAGS ""
#define KERNEL_ASMFLAGS ""
#define KERNEL_LDFLAGS "_--emit-relocs"

