#pragma once
#define MODULE_LIBS ""
#define MODULE_STATIC_LIBS ""
#define MODULE_COMPILEFLAGS "-Iglobal/include_-Isystem/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba/dlopen-indirect-deps-test-libb/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64/config-user.h"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba/dlopen-indirect-deps-test-libb/libb.c"
#define MODULE_HEADER_DEPS ""
#define MODULE_TYPE "userlib"

