#pragma once
#define LK 1
#define _KERNEL 1
#define ZIRCON_TOOLCHAIN 1
#define WITH_PANIC_BACKTRACE 1
#define WITH_FRAME_POINTERS 1
#define WITH_DEBUG_LINEBUFFER 1
#define WITH_TARGET_PC 1
#define PLATFORM_SUPPORTS_PANIC_SHELL 1
#define WITH_PLATFORM_PC 1
#define ARCH_X86 1
#define KERNEL_BASE 0xffffffff80100000
#define KERNEL_SIZE 0x40000000
#define KERNEL_LOAD_OFFSET 0x00100000
#define SMP_MAX_CPUS 16
#define WITH_ARCH_X86 1
#define WITH_TOP 1
#define WITH_ARCH_X86_PAGE_TABLES 1
#define WITH_DEV_INTEL_RNG 1
#define WITH_DEV_INTERRUPT 1
#define WITH_DEV_IOMMU_DUMMY 1
#define WITH_DEV_PCIE 1
#define WITH_KERNEL 1
#define WITH_LIB_BITMAP 1
#define WITH_LIB_CBUF 1
#define WITH_LIB_CODE_PATCHING 1
#define WITH_LIB_DEBUGCOMMANDS 1
#define WITH_LIB_DEBUGLOG 1
#define WITH_LIB_FBL 1
#define WITH_LIB_FIXED_POINT 1
#define WITH_LIB_GFXCONSOLE 1
#define WITH_LIB_KTRACE 1
#define WITH_LIB_MEMORY_LIMIT 1
#define WITH_LIB_MTRACE 1
#define WITH_LIB_POW2_RANGE_ALLOCATOR 1
#define WITH_LIB_SMBIOS 1
#define WITH_LIB_USERBOOT 1
#define WITH_LIB_VERSION 1
#define WITH_OBJECT 1
#define WITH_PLATFORM 1
#define WITH_SYSCALLS 1
#define WITH_TARGET 1
#define WITH_TESTS 1
#define WITH_LIB_ACPICA 1
#define WITH_LIB_CKSUM 1
#define WITH_DEV_HW_RNG 1
#define WITH_DEV_UDISPLAY 1
#define WITH_LIB_CONSOLE 1
#define WITH_LIB_COUNTERS 1
#define WITH_LIB_CRYPTO 1
#define WITH_LIB_DEBUG 1
#define WITH_LIB_EXPLICIT_MEMORY 1
#define WITH_LIB_GFX 1
#define WITH_LIB_HEADER_TESTS 1
#define WITH_LIB_HEAP 1
#define WITH_LIB_HWREG 1
#define WITH_LIB_HYPERVISOR 1
#define WITH_LIB_LIBC 1
#define WITH_LIB_OOM 1
#define WITH_LIB_PCI 1
#define WITH_LIB_REGION_ALLOC 1
#define WITH_LIB_UNITTEST 1
#define WITH_LIB_USER_COPY 1
#define WITH_LIB_VDSO 1
#define WITH_LIB_ZXCPP 1
#define WITH_VM 1
#define WITH_ARCH_X86_HYPERVISOR 1
#define WITH_LIB_HEAP_CMPCTMALLOC 1
#define WITH_LIB_IO 1
#define WITH_LIB_PRETTY 1
#define WITH_LIB_CRYPTOLIB 1
#define WITH_LIB_JITTERENTROPY 1
#define WITH_LIB_QRCODEGEN 1
#define WITH_LIB_UBORINGSSL 1
#define PROJECT_X64 1
#define PROJECT "x64"
#define TARGET_PC 1
#define TARGET "pc"
#define PLATFORM_PC 1
#define PLATFORM "pc"
#define ARCH_X86 1
#define ARCH "x86"
#define BOOT_HEADER_SIZE 0x70
#define KERNEL_IMAGE "./build-x64/zircon.elf.bin"
#define KERNEL_INCLUDES "-I./build-x64_-Ikernel/include_-Ikernel/target/pc/include_-Ikernel/platform/pc/include_-Ikernel/arch/x86/include_-Ikernel/top/include_-Ikernel/arch/x86/page_tables/include_-Ikernel/arch/x86/page_tables/include_-Ikernel/dev/intel_rng/include_-Ikernel/dev/interrupt/include_-Ikernel/dev/iommu/dummy/include_-Ikernel/dev/pcie/include_-Ikernel/kernel/include_-Isystem/ulib/bitmap/include_-Ikernel/lib/bitmap/include_-Ikernel/lib/cbuf/include_-Ikernel/lib/code_patching/include_-Ikernel/lib/debugcommands/include_-Ikernel/lib/debuglog/include_-Ikernel/lib/fbl/include_-Isystem/ulib/fbl/include_-Ikernel/lib/fbl/include_-Ikernel/lib/fixed_point/include_-Ikernel/lib/gfxconsole/include_-Ikernel/lib/ktrace/include_-Ikernel/lib/memory_limit/include_-Ikernel/lib/mtrace/include_-Ikernel/lib/pow2_range_allocator/include_-Isystem/ulib/smbios/include_-Ikernel/lib/smbios/include_-Ikernel/lib/userboot/include_-Ikernel/lib/version/include_-Ikernel/object/include_-Ikernel/platform/include_-Ikernel/syscalls/include_-Ikernel/target/include_-Ikernel/tests/include_-Ithird_party/lib/acpica/source/include_-Ithird_party/lib/acpica/include_-Ithird_party/ulib/cksum/include_-Ithird_party/lib/cksum/include_-Ikernel/dev/hw_rng/include_-Ikernel/dev/udisplay/include_-Ikernel/lib/console/include_-Ikernel/lib/counters/include_-Ikernel/lib/crypto/include_-Ikernel/lib/debug/include_-Isystem/ulib/explicit-memory/include_-Ikernel/lib/explicit-memory/include_-Ikernel/lib/gfx/include_-Ikernel/lib/header_tests/include_-Ikernel/lib/heap/include_-Ikernel/lib/heap/include_-Isystem/ulib/hwreg/include_-Ikernel/lib/hwreg/include_-Ikernel/lib/hypervisor/include_-Ikernel/lib/libc/include_-Ikernel/lib/oom/include_-Ikernel/lib/pci/include_-Ikernel/lib/pci/include_-Isystem/ulib/region-alloc/include_-Ikernel/lib/region-alloc/include_-Ikernel/lib/unittest/include_-Ikernel/lib/user_copy/include_-Ikernel/lib/vdso/include_-Isystem/ulib/zxcpp/include_-Ikernel/lib/zxcpp/include_-Ikernel/vm/include_-Ikernel/arch/x86/hypervisor/include_-Ikernel/lib/heap/cmpctmalloc/include_-Ikernel/lib/io/include_-Isystem/ulib/pretty/include_-Ikernel/lib/pretty/include_-Ithird_party/ulib/cryptolib/include_-Ithird_party/lib/cryptolib/include_-Ithird_party/lib/jitterentropy/include_-Ithird_party/lib/jitterentropy/include_-Ithird_party/ulib/qrcodegen/include_-Ithird_party/lib/qrcodegen/include_-Ithird_party/ulib/uboringssl/include_-Ithird_party/lib/uboringssl/include"
#define KERNEL_COMPILEFLAGS "-ffreestanding_-include_./build-x64/config-kernel.h_-Wformat=2_-Wvla_-Wformat-signedness_-fno-exceptions_-fno-unwind-tables_-fno-omit-frame-pointer_-falign-jumps=1_-falign-loops=1_-falign-functions=4_-msoft-float_-mno-mmx_-mno-sse_-mno-sse2_-mno-3dnow_-mno-avx_-mno-avx2_-mno-80387_-mno-fp-ret-in-387_-fPIE_-include_kernel/include/hidden.h_-mno-red-zone_-mskip-rax-setup"
#define KERNEL_CFLAGS "-Wmissing-prototypes"
#define KERNEL_CPPFLAGS ""
#define KERNEL_ASMFLAGS ""
#define KERNEL_LDFLAGS "_--emit-relocs"

