#pragma once
#define MODULE_LIBS "system/ulib/c_system/ulib/fdio_system/ulib/unittest_system/ulib/zircon_"
#define MODULE_STATIC_LIBS "system/ulib/zxcpp_system/ulib/fbl_system/ulib/zx_"
#define MODULE_COMPILEFLAGS "-I./build-arm64-release/system/ulib/c/gen/include_-I./build-arm64-release/system/ulib/fbl/gen/include_-I./build-arm64-release/system/ulib/fdio/gen/include_-I./build-arm64-release/system/ulib/unittest/gen/include_-I./build-arm64-release/system/ulib/zircon/gen/include_-I./build-arm64-release/system/ulib/zx/gen/include_-I./build-arm64-release/system/ulib/zxcpp/gen/include_-Iglobal/include_-Isystem/ulib/c/include_-Isystem/ulib/fbl/include_-Isystem/ulib/fdio/include_-Isystem/ulib/unittest/include_-Isystem/ulib/zircon/include_-Isystem/ulib/zx/include_-Isystem/ulib/zxcpp/include_-Isystem/utest/fbl/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-arm64-release/config-user.h_./build-arm64-release/system/ulib/c/gen-hdr.stamp_./build-arm64-release/system/ulib/fbl/gen-hdr.stamp_./build-arm64-release/system/ulib/fdio/gen-hdr.stamp_./build-arm64-release/system/ulib/unittest/gen-hdr.stamp_./build-arm64-release/system/ulib/zircon/gen-hdr.stamp_./build-arm64-release/system/ulib/zx/gen-hdr.stamp_./build-arm64-release/system/ulib/zxcpp/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/utest/fbl/algorithm_tests.cpp_system/utest/fbl/array_tests.cpp_system/utest/fbl/atomic_tests.cpp_system/utest/fbl/auto_call_tests.cpp_system/utest/fbl/forward_tests.cpp_system/utest/fbl/function_tests.cpp_system/utest/fbl/initializer_list_tests.cpp_system/utest/fbl/integer_sequence_tests.cpp_system/utest/fbl/intrusive_container_tests.cpp_system/utest/fbl/intrusive_doubly_linked_list_tests.cpp_system/utest/fbl/intrusive_hash_table_dll_tests.cpp_system/utest/fbl/intrusive_hash_table_sll_tests.cpp_system/utest/fbl/intrusive_singly_linked_list_tests.cpp_system/utest/fbl/intrusive_wavl_tree_tests.cpp_system/utest/fbl/main.c_system/utest/fbl/memory_probe_tests.cpp_system/utest/fbl/recycler_tests.cpp_system/utest/fbl/ref_counted_tests.cpp_system/utest/fbl/ref_ptr_tests.cpp_system/utest/fbl/slab_allocator_tests.cpp_system/utest/fbl/string_buffer_tests.cpp_system/utest/fbl/string_piece_tests.cpp_system/utest/fbl/string_printf_tests.cpp_system/utest/fbl/string_tests.cpp_system/utest/fbl/string_traits_tests.cpp_system/utest/fbl/type_support_tests.cpp_system/utest/fbl/unique_fd_tests.cpp_system/utest/fbl/unique_free_ptr_tests.cpp_system/utest/fbl/unique_ptr_tests.cpp_system/utest/fbl/vector_tests.cpp_system/utest/fbl/vmo_vmar_tests.cpp"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/fbl_system/ulib/fdio_system/ulib/unittest_system/ulib/zircon_system/ulib/zx_system/ulib/zxcpp"
#define MODULE_TYPE "usertest"

