#pragma once
#define MODULE_LIBS "system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba"
#define MODULE_STATIC_LIBS ""
#define MODULE_COMPILEFLAGS "-I./build-x64/system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba/gen/include_-Iglobal/include_-Isystem/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba/include_-Isystem/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64/config-user.h_./build-x64/system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/test-module.c"
#define MODULE_HEADER_DEPS "system/utest/dlopen-indirect-deps/dlopen-indirect-deps-test-module/dlopen-indirect-deps-test-liba"
#define MODULE_TYPE "userlib"

