#pragma once
#define MODULE_LIBS "system/ulib/fdio_system/ulib/launchpad_system/ulib/zircon_system/ulib/c"
#define MODULE_STATIC_LIBS "system/ulib/inet6_system/ulib/tftp_system/ulib/sync"
#define MODULE_COMPILEFLAGS "-I./build-x64-release/system/ulib/c/gen/include_-I./build-x64-release/system/ulib/fdio/gen/include_-I./build-x64-release/system/ulib/inet6/gen/include_-I./build-x64-release/system/ulib/launchpad/gen/include_-I./build-x64-release/system/ulib/sync/gen/include_-I./build-x64-release/system/ulib/tftp/gen/include_-I./build-x64-release/system/ulib/zircon/gen/include_-Iglobal/include_-Isystem/core/netsvc/include_-Isystem/ulib/c/include_-Isystem/ulib/fdio/include_-Isystem/ulib/inet6/include_-Isystem/ulib/launchpad/include_-Isystem/ulib/sync/include_-Isystem/ulib/tftp/include_-Isystem/ulib/zircon/include_-Ithird_party/ulib/musl/include"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_SRCDEPS "./build-x64-release/config-user.h_./build-x64-release/system/ulib/c/gen-hdr.stamp_./build-x64-release/system/ulib/fdio/gen-hdr.stamp_./build-x64-release/system/ulib/inet6/gen-hdr.stamp_./build-x64-release/system/ulib/launchpad/gen-hdr.stamp_./build-x64-release/system/ulib/sync/gen-hdr.stamp_./build-x64-release/system/ulib/tftp/gen-hdr.stamp_./build-x64-release/system/ulib/zircon/gen-hdr.stamp"
#define MODULE_DEPS ""
#define MODULE_SRCS "system/core/netsvc/debuglog.c_system/core/netsvc/device_id.c_system/core/netsvc/netboot.c_system/core/netsvc/netfile.c_system/core/netsvc/netsvc.c_system/core/netsvc/tftp.c"
#define MODULE_HEADER_DEPS "system/ulib/c_system/ulib/fdio_system/ulib/inet6_system/ulib/launchpad_system/ulib/sync_system/ulib/tftp_system/ulib/zircon"
#define MODULE_TYPE "userapp"

